import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Provider from "./provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <Navbar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
